"""Data structures and state models for the local voice input subsystem."""

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class VoiceState(str, Enum):
    """Lifecycle state of the local voice capture and transcription pipeline."""
    IDLE = "idle"
    RECORDING = "recording"
    TRANSCRIBING = "transcribing"
    COMPLETED = "completed"
    ERROR = "error"


class AudioDevice(BaseModel):
    """Metadata representing an available audio input device (microphone)."""
    id: int
    name: str
    hostapi: str
    max_input_channels: int
    default_samplerate: float
    is_default: bool = False

    @property
    def display_name(self) -> str:
        """Formatted human-readable device name."""
        suffix = " (Default)" if self.is_default else ""
        return f"{self.name}{suffix}"


class TranscriptionResult(BaseModel):
    """Structured transcription output generated by local speech-to-text."""
    text: str
    language: Optional[str] = None
    duration: float = 0.0
    provider: str = "faster-whisper"
    confidence: Optional[float] = None


class VoiceStatus(BaseModel):
    """Diagnostic status model for voice input readiness and device state."""
    enabled: bool = True
    state: VoiceState = VoiceState.IDLE
    selected_mic: Optional[str] = None
    default_mic: Optional[str] = None
    model_name: str = "base"
    is_available: bool = True
    error_message: Optional[str] = None
