"""Data structures and state models for the local text-to-speech subsystem."""

from enum import Enum
from pathlib import Path
from typing import Optional
from pydantic import BaseModel, Field


class TTSState(str, Enum):
    """Lifecycle state of the local text-to-speech synthesis and playback pipeline."""
    IDLE = "idle"
    SYNTHESIZING = "synthesizing"
    SPEAKING = "speaking"
    STOPPING = "stopping"
    ERROR = "error"


class VoiceInfo(BaseModel):
    """Metadata describing an available local speech synthesis voice."""
    id: str
    name: str
    language: str = "en"
    gender: Optional[str] = None

    @property
    def display_name(self) -> str:
        return self.name


class AudioOutputDevice(BaseModel):
    """Metadata representing an available audio playback output device (speaker/headphones)."""
    id: int
    name: str
    hostapi: str
    max_output_channels: int
    default_samplerate: float
    is_default: bool = False

    @property
    def display_name(self) -> str:
        suffix = " (Default)" if self.is_default else ""
        return f"{self.name}{suffix}"


class TTSResult(BaseModel):
    """Structured result generated by a local text-to-speech synthesis operation."""
    audio_path: Optional[Path] = None
    duration: float = 0.0
    text: str
    voice: str = "default"
    provider: str = "pyttsx3"
    success: bool = True


class TTSStatus(BaseModel):
    """Diagnostic status snapshot for text-to-speech readiness, state, and output routing."""
    enabled: bool = True
    state: TTSState = TTSState.IDLE
    auto_speak: bool = False
    selected_voice: Optional[str] = None
    selected_output: Optional[str] = None
    is_available: bool = True
    error_message: Optional[str] = None
