"""Domain models and data representations for the Multimodal Vision subsystem."""

from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Optional
import uuid
from pydantic import BaseModel, Field


class ImageSource(str, Enum):
    """Origin source of the image input."""

    FILE = "file"
    SCREENSHOT = "screenshot"
    CLIPBOARD = "clipboard"
    BROWSER = "browser"


class ImageFormat(str, Enum):
    """Validated image format categories."""

    PNG = "png"
    JPEG = "jpeg"
    WEBP = "webp"
    BMP = "bmp"
    UNKNOWN = "unknown"


class ImageInput(BaseModel):
    """Validated image representation with metadata, byte sizes, and optional base64 payload."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier for the image input")
    source: ImageSource = Field(description="Origin source category of this image")
    path: Optional[str] = Field(default=None, description="Local filesystem path if saved on disk")
    filename: str = Field(default="image.png", description="Display filename for UI and logs")
    mime_type: str = Field(default="image/png", description="MIME type (e.g. image/png, image/jpeg)")
    image_format: ImageFormat = Field(default=ImageFormat.PNG, description="Detected image format")
    width: int = Field(default=0, ge=0, description="Image width in pixels")
    height: int = Field(default=0, ge=0, description="Image height in pixels")
    size_bytes: int = Field(default=0, ge=0, description="Image byte size")
    sha256_hash: str = Field(default="", description="SHA-256 hash for deduplication and cache indexing")
    base64_data: Optional[str] = Field(default=None, description="Base64-encoded string for Ollama multimodal API")
    is_temp: bool = Field(default=False, description="Whether the file path is a temporary file requiring cleanup")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Creation timestamp")

    @property
    def dimensions_str(self) -> str:
        """Return human-readable dimension string (e.g. '1920x1080')."""
        return f"{self.width}x{self.height}" if self.width > 0 and self.height > 0 else "Unknown dimensions"

    @property
    def size_kb(self) -> float:
        """Return file size in kilobytes."""
        return round(self.size_bytes / 1024.0, 1)


class VisionResult(BaseModel):
    """Structured response from vision model analysis."""

    text: str = Field(description="Analysis or textual response generated by the vision model")
    model: str = Field(description="Model used for vision inference")
    processing_time_seconds: float = Field(default=0.0, description="Inference processing latency in seconds")
    confidence: Optional[float] = Field(default=None, description="Model confidence score if provided")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional diagnostic metadata")


class VisionStatus(BaseModel):
    """Real-time availability status of the multimodal vision subsystem."""

    is_available: bool = Field(description="Whether a vision-capable model is installed and accessible")
    active_model: Optional[str] = Field(default=None, description="Name of the selected vision model")
    installed_vision_models: list[str] = Field(default_factory=list, description="List of installed vision-capable models")
    error_message: Optional[str] = Field(default=None, description="Diagnostic error or reason if unavailable")
