from datetime import datetime, timezone
from enum import Enum
from typing import TYPE_CHECKING, Any, Iterator, Optional, Union
import uuid

from pydantic import BaseModel, Field, model_validator

from app.core.config import Settings, get_settings
from app.core.exceptions import (
    ConversationNotFoundError,
    InvalidMessageError,
    ModelError,
)
from app.core.logging import get_logger
from app.core.ollama_client import OllamaClient

if TYPE_CHECKING:
    from app.memory.manager import MemoryManager
    from app.memory.repository import ConversationRepository

logger = get_logger("conversation")



class Role(str, Enum):
    """Allowed participant roles in a conversation."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class Message(BaseModel):
    """Structured representation of a single conversation turn."""

    role: Role = Field(description="Participant role: system, user, assistant, or tool")
    content: str = Field(default="", description="Textual content of the message")
    tool_calls: Optional[list[dict[str, Any]]] = Field(
        default=None, description="Optional tool calls generated by assistant"
    )
    name: Optional[str] = Field(default=None, description="Optional tool name when role is tool")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when message was recorded",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extensible metadata (for future tool-calls, token stats, etc.)",
    )

    @model_validator(mode="before")
    @classmethod
    def validate_message(cls, data: Any) -> Any:
        if isinstance(data, dict):
            content = data.get("content", "")
            role = data.get("role")
            tool_calls = data.get("tool_calls")
            if not isinstance(content, str):
                raise InvalidMessageError(f"Message content must be a string, got {type(content).__name__}")
            # Empty content allowed only if assistant has tool_calls or role is tool
            is_tool = role in (Role.TOOL, "tool")
            is_assistant_tool_call = role in (Role.ASSISTANT, "assistant") and bool(tool_calls)
            if not content.strip() and not is_assistant_tool_call and not is_tool:
                raise InvalidMessageError("Message content cannot be empty or whitespace-only")
        return data

    def to_dict(self) -> dict[str, Any]:
        """Format message as dictionary suitable for Ollama API."""
        payload: dict[str, Any] = {"role": self.role.value, "content": self.content}
        if self.tool_calls:
            formatted_calls = []
            for tc in self.tool_calls:
                if "function" in tc:
                    formatted_calls.append(tc)
                else:
                    formatted_calls.append({
                        "function": {
                            "name": tc.get("name", ""),
                            "arguments": tc.get("arguments", {}),
                        }
                    })
            payload["tool_calls"] = formatted_calls
        if self.name:
            payload["name"] = self.name
        return payload



class Conversation:
    """Represents a discrete multi-turn conversation session with history trimming and optional persistence."""

    def __init__(
        self,
        conversation_id: Optional[str] = None,
        system_prompt: Optional[str] = None,
        max_messages: int = 50,
        repository: Optional[Any] = None,
    ) -> None:
        self.id: str = conversation_id or str(uuid.uuid4())
        self.created_at: datetime = datetime.now(timezone.utc)
        self.system_prompt: Optional[str] = system_prompt.strip() if system_prompt and system_prompt.strip() else None
        self.max_messages: int = max(1, max_messages)
        self.repository = repository
        self._messages: list[Message] = []

        if self.repository:
            try:
                for rec in self.repository.get_messages(self.id):
                    self._messages.append(
                        Message(
                            role=Role(rec.role),
                            content=rec.content,
                        )
                    )
            except Exception as err:
                logger.warning("Could not pre-load messages for conversation %s: %s", self.id, err)

    def add_message(
        self,
        role: Union[Role, str],
        content: str = "",
        tool_calls: Optional[list[dict[str, Any]]] = None,
        name: Optional[str] = None,
        metadata: Optional[dict[str, Any]] = None,
    ) -> Message:
        """Add a validated message to the conversation history."""
        # Validate role
        if isinstance(role, Role):
            validated_role = role
        elif isinstance(role, str):
            try:
                validated_role = Role(role.lower().strip())
            except ValueError:
                valid_roles = [r.value for r in Role]
                raise InvalidMessageError(f"Invalid role '{role}'. Must be one of {valid_roles}")
        else:
            raise InvalidMessageError(f"Role must be a string or Role enum, got {type(role).__name__}")

        # Construct Message (triggers model validation)
        msg = Message(
            role=validated_role,
            content=content,
            tool_calls=tool_calls,
            name=name,
            metadata=metadata or {},
        )

        self._messages.append(msg)
        self._trim_history()

        if self.repository:
            try:
                self.repository.append_message(self.id, validated_role.value, content)
            except Exception as err:
                logger.error("Failed to persist message to repository: %s", err)

        logger.debug("Conversation %s added %s message (total: %d)", self.id, validated_role.value, len(self._messages))
        return msg

    def add_user_message(self, content: str, metadata: Optional[dict[str, Any]] = None) -> Message:
        """Helper to add a user message."""
        return self.add_message(Role.USER, content, metadata=metadata)

    def add_assistant_message(
        self,
        content: str = "",
        tool_calls: Optional[list[dict[str, Any]]] = None,
        metadata: Optional[dict[str, Any]] = None,
    ) -> Message:
        """Helper to add an assistant message with optional tool_calls."""
        return self.add_message(Role.ASSISTANT, content, tool_calls=tool_calls, metadata=metadata)

    def add_tool_message(
        self,
        content: str,
        name: str,
        metadata: Optional[dict[str, Any]] = None,
    ) -> Message:
        """Helper to add a tool result message."""
        return self.add_message(Role.TOOL, content, name=name, metadata=metadata)

    @property
    def messages(self) -> list[Message]:
        """Return an immutable copy of the conversation messages."""
        return self.get_messages()

    def get_messages(self) -> list[Message]:
        """Return an immutable defensive copy of the conversation messages."""
        return [m.model_copy(deep=True) for m in self._messages]


    def get_messages_for_llm(self, extra_system_context: Optional[str] = None) -> list[dict[str, str]]:
        """Return message list formatted for Ollama, prepending system prompt and optional extra context."""
        payload: list[dict[str, str]] = []
        sys_parts = []
        if self.system_prompt:
            sys_parts.append(self.system_prompt)
        if extra_system_context and extra_system_context.strip():
            sys_parts.append(extra_system_context.strip())

        if sys_parts:
            payload.append({"role": Role.SYSTEM.value, "content": "\n\n".join(sys_parts)})

        for msg in self._messages:
            payload.append(msg.to_dict())
        return payload

    def message_count(self) -> int:
        """Return the number of stored conversational messages."""
        return len(self._messages)

    def clear(self) -> None:
        """Clear all conversation turns while preserving conversation ID and system prompt."""
        self._messages.clear()
        logger.info("Conversation %s history cleared", self.id)

    def reset(self) -> None:
        """Alias for clear()."""
        self.clear()

    def _trim_history(self) -> None:
        """Trim oldest non-system messages when exceeding max_messages limit."""
        if len(self._messages) > self.max_messages:
            excess = len(self._messages) - self.max_messages
            self._messages = self._messages[excess:]
            logger.debug("Conversation %s trimmed %d oldest message(s)", self.id, excess)


class ConversationManager:
    """Orchestrates conversations, active sessions, persistence, and communication with OllamaClient."""

    def __init__(
        self,
        client: Optional[OllamaClient] = None,
        settings: Optional[Settings] = None,
        system_prompt: Optional[str] = None,
        max_messages: Optional[int] = None,
        memory_manager: Optional[Any] = None,
    ) -> None:
        self.settings: Settings = settings or get_settings()
        self.client: OllamaClient = client or OllamaClient(settings=self.settings)
        self.system_prompt: str = (
            system_prompt if system_prompt is not None else self.settings.system_prompt
        )
        self.max_messages: int = (
            max_messages if max_messages is not None else self.settings.max_conversation_messages
        )
        self.memory_manager = memory_manager
        self.conversation_repository = memory_manager.conversations if memory_manager else None

        self._conversations: dict[str, Conversation] = {}
        # Create and track default active conversation
        default_conv = self.create_conversation()
        self._active_conversation_id: str = default_conv.id
        logger.info("ConversationManager initialized with active conversation %s", self._active_conversation_id)

    @property
    def active_conversation(self) -> Conversation:
        """Return the current active conversation."""
        return self._conversations[self._active_conversation_id]

    def create_conversation(
        self,
        conversation_id: Optional[str] = None,
        system_prompt: Optional[str] = None,
        max_messages: Optional[int] = None,
    ) -> Conversation:
        """Create a new conversation session and register it."""
        prompt = system_prompt if system_prompt is not None else self.system_prompt
        max_limit = max_messages if max_messages is not None else self.max_messages
        conv = Conversation(
            conversation_id=conversation_id,
            system_prompt=prompt,
            max_messages=max_limit,
            repository=self.conversation_repository,
        )
        if self.conversation_repository:
            self.conversation_repository.create_conversation(conv.id, title="New Conversation")

        self._conversations[conv.id] = conv
        self._active_conversation_id = conv.id
        logger.info("Created new conversation session %s", conv.id)
        return conv

    def load_conversation(self, conversation_id: str) -> Conversation:
        """Load an existing conversation from repository or memory and set as active."""
        if conversation_id in self._conversations:
            self._active_conversation_id = conversation_id
            return self._conversations[conversation_id]

        if self.conversation_repository:
            rec = self.conversation_repository.get_conversation(conversation_id)
            if not rec:
                raise ConversationNotFoundError(f"Conversation with ID '{conversation_id}' not found")

            conv = Conversation(
                conversation_id=conversation_id,
                system_prompt=self.system_prompt,
                max_messages=self.max_messages,
                repository=self.conversation_repository,
            )
            self._conversations[conv.id] = conv
            self._active_conversation_id = conv.id
            logger.info("Loaded persistent conversation %s ('%s')", conv.id, rec.title)
            return conv

        raise ConversationNotFoundError(f"Conversation with ID '{conversation_id}' not found")

    def list_conversations(self, limit: int = 50) -> list[Any]:
        """List active and persisted conversations."""
        if self.conversation_repository:
            return self.conversation_repository.list_conversations(limit=limit)
        return list(self._conversations.values())

    def delete_conversation(self, conversation_id: str) -> bool:
        """Delete a conversation session from active memory and persistent database."""
        self._conversations.pop(conversation_id, None)
        deleted = False
        if self.conversation_repository:
            deleted = self.conversation_repository.delete_conversation(conversation_id)

        if self._active_conversation_id == conversation_id:
            new_conv = self.create_conversation()
            self._active_conversation_id = new_conv.id

        return deleted

    def get_conversation(self, conversation_id: Optional[str] = None) -> Conversation:
        """Retrieve a conversation by ID, or return the active conversation."""
        if conversation_id is None:
            return self.active_conversation
        if conversation_id not in self._conversations:
            # Attempt to load from repository
            if self.conversation_repository:
                try:
                    return self.load_conversation(conversation_id)
                except ConversationNotFoundError:
                    pass
            raise ConversationNotFoundError(f"Conversation with ID '{conversation_id}' not found")
        return self._conversations[conversation_id]

    def set_active_conversation(self, conversation_id: str) -> Conversation:
        """Switch active conversation to the specified ID."""
        conv = self.get_conversation(conversation_id)
        self._active_conversation_id = conv.id
        return conv

    def reset(self, conversation_id: Optional[str] = None) -> None:
        """Reset history for the specified or active conversation."""
        conv = self.get_conversation(conversation_id)
        conv.reset()


    def send_message(
        self,
        text: str,
        model: Optional[str] = None,
        conversation_id: Optional[str] = None,
    ) -> str:
        """Send user message to Ollama, update conversation history, and return response text."""
        conv = self.get_conversation(conversation_id)

        # Validate and record user message
        conv.add_user_message(text)

        payload = conv.get_messages_for_llm()
        logger.info("Conversation %s sending request with %d messages", conv.id, len(payload))

        try:
            response_text = self.client.chat(payload, model=model)
            # Record assistant message only upon successful completion
            conv.add_assistant_message(response_text)
            logger.info("Conversation %s successfully received assistant response", conv.id)
            return response_text
        except Exception as err:
            logger.error("Conversation %s model request failed: %s", conv.id, err)
            # User message is retained, but NO assistant message is recorded
            raise

    def stream_message(
        self,
        text: str,
        model: Optional[str] = None,
        conversation_id: Optional[str] = None,
    ) -> Iterator[str]:
        """Stream assistant response tokens, accumulating and saving full response exactly once."""
        conv = self.get_conversation(conversation_id)

        # Validate and record user message
        conv.add_user_message(text)

        payload = conv.get_messages_for_llm()
        logger.debug("Conversation %s starting streaming request with %d messages", conv.id, len(payload))

        accumulated_chunks: list[str] = []

        try:
            for chunk in self.client.stream_chat(payload, model=model):
                accumulated_chunks.append(chunk)
                yield chunk

            # On successful completion of stream, record assistant response exactly once
            full_response = "".join(accumulated_chunks)
            if full_response.strip():
                conv.add_assistant_message(full_response)
                logger.debug("Conversation %s recorded completed stream response (%d chars)", conv.id, len(full_response))
            else:
                logger.warning("Conversation %s stream yielded empty response; not recorded in history", conv.id)


        except Exception as err:
            logger.error("Conversation %s streaming request failed: %s", conv.id, err)
            # Incomplete stream is NOT recorded as a successful assistant message
            raise
