"""Permission decisions, execution contexts, and security evaluation models."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
import uuid

from pydantic import BaseModel, Field

from app.tools.base import RiskLevel


class PermissionDecision(str, Enum):
    """Possible outcomes of security policy evaluation."""

    ALLOW = "ALLOW"
    DENY = "DENY"
    CONFIRM = "CONFIRM"


class ExecutionContext(BaseModel):
    """Contextual metadata surrounding a tool execution attempt."""

    request_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier correlating tool evaluation, approval, and execution",
    )
    tool_name: str = Field(description="Name of the requested tool")
    arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Validated arguments provided for tool execution",
    )
    risk_level: RiskLevel = Field(description="Assigned risk level of the tool")
    source: str = Field(default="agent", description="Caller/trigger source (e.g. agent, cli, system)")
    interactive: bool = Field(default=False, description="Whether execution is taking place in an interactive session")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when the tool request was initiated",
    )


class SecurityDecision(BaseModel):
    """Structured security decision generated by the policy engine."""

    decision: PermissionDecision = Field(description="Final evaluation decision: ALLOW, DENY, or CONFIRM")
    reason: str = Field(description="Explanation or rationale for the security decision")
    tool_name: str = Field(description="Target tool name")
    risk_level: RiskLevel = Field(description="Assigned risk level of the tool")
    request_id: str = Field(description="Request identifier for audit correlation")
    requires_user_confirmation: bool = Field(
        default=False,
        description="Indicates whether user confirmation is required before proceeding",
    )
